spring:
  application:
    name: admin-eam-back
  datasource:
    url: jdbc:h2:C:\h2\db
    username: sa
    password: test
  h2:
    console:
      enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sk.eadmin.biz.* 
  configuration:
    map-underscore-to-camel-case: true
